runtime: python36

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

- url: /chromedriver.exe
  static_dir: static/ChromeDriverWin32/chromedriver.exe
  upload: chromedriver.exe

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /user_pulls
  static_dir: static/user_pulls

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto



  